[{if $aVariantSelections && $aVariantSelections.selections}]
    [{oxscript include="js/widgets/oxajax.min.js" priority=10 }]
    [{oxscript include="js/widgets/oxarticlevariant.min.js" priority=10 }]
    [{oxscript add="$( '#variants' ).oxArticleVariant();"}]
    [{assign var="blCanBuy" value=$aVariantSelections.blPerfectFit}]
    [{if !$blHasActiveSelections}]
        [{if !$blCanBuy && !$oDetailsProduct->isParentNotBuyable()}]
            [{assign var="blCanBuy" value=true}]
        [{/if}]
    [{/if}]
    <div id="variants" class="selectorsBox variant-dropdown js-fnSubmit">
        [{assign var="blHasActiveSelections" value=false}]
        [{foreach from=$aVariantSelections.selections item=oList key=iKey}]
            [{if $oList->getActiveSelection()}]
                [{assign var="blHasActiveSelections" value=true}]
            [{/if}]
            [{if $oList->isIconSelectlist()}]
                [{include file="widget/product/selectbox-icon.tpl" oSelectionList=$oList iKey=$iKey blInDetails=true}]
            [{else}]
                [{include file="widget/product/selectbox.tpl" oSelectionList=$oList iKey=$iKey blInDetails=true}]
            [{/if}]

        [{/foreach}]
    </div>
[{/if}]